# Generated by Django 4.0.2 on 2022-02-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackaway', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Safengine',
            new_name='Search',
        ),
    ]
